DROP TABLE IF EXISTS scores CASCADE;
CREATE TABLE scores(
    id SERIAL PRIMARY KEY NOT NULL,
    score INTEGER,
    time VARCHAR,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
);